### ISSUE TITLE
Conflicting information in iOS SDK reference and LDClient Class Reference

### ISSUE THREAD

**Issue by RobotK** [launchdarkly/LaunchDarkly-Docs#154]
In the iOS SDK reference, the "[Terminating the client instance](https://docs.launchdarkly.com/sdk/client-side/ios#terminating-the-client-instance)" says:

> Lastly, when your application is about to terminate, shut down the LDClient instance. This ensures that the client releases any resources it is using, and that any pending analytics events are delivered to LaunchDarkly. If your application quits without this shutdown step, you may not see your requests and users on the dashboard, because they are derived from analytics events. This is something you only need to do one time.

But in the LDClient Class Reference, [the documentation for the `close` method](https://launchdarkly.github.io/ios-client-sdk/Classes/LDClient.html#/s:12LaunchDarkly8LDClientC5closeyyF) says:

> There is almost no reason to stop the LDClient. Normally, set the LDClient offline to stop communication with the LaunchDarkly servers. Stop the LDClient to stop recording events. There is no need to stop the LDClient prior to suspending, moving to the background, or terminating the app. The SDK will respond to these events as the system requires and as configured in LDConfig.

I'm assuming the class reference is correct, and the SDK reference is wrong, but whichever is incorrect should be fixed.

**Comment by scribblingfox** [comment]
Hey @RobotK! Thanks for your close attention to our docs! @bwoskow-ld, can you give some advice here please?

**Comment by bwoskow-ld** [comment]
The iOS SDK reference page is correct. The difference between the two documented descriptions is subtle. The main reason to be sure to call `close` is so that your app sends any queued events which have not yet been sent to LaunchDarkly. The iOS SDK reference page makes this clear but the class reference does not.

I'll file a ticket on our internal backlog to improve the class reference. Note that this content is auto-generated from code comments and as such will be fixed in the SDK repository itself, rather than this documentation repository. I'll leave it up to you @scribblingfox to decide if you want to keep this ticket open in the meantime.

**Comment by RobotK** [comment]
Thanks @bwoskow-ld! I'll update our code appropriately.

**Comment by bwoskow-ld** [comment]
Closing this ticket for the reasons mentioned in my prior comment -- there's a ticket on our internal backlog to improve the auto-generated API documentation, and there's nothing more to do in this documentation repository.
