### ISSUE TITLE
Improve the schema explanation for the DynamoDB persistent storage option

### ISSUE THREAD

**Issue by disposedtrolley** [launchdarkly/LaunchDarkly-Docs#201]
Hello!

I was wondering if it'd be sensible to elaborate on the [DynamoDB schema requirements](https://docs.launchdarkly.com/sdk/features/storing-data/dynamodb#how-the-sdks-store-data-in-dynamodb) in the documentation?

I ran into an issue trying to set up a local Relay Proxy with [DynamoDB Local](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html), where initialisation fails due to an incorrect table schema:

```
Data store returned error: failed to get existing items prior to Init: ValidationException: Query condition missed key schema element
```

I created the tables with a single `key` attribute of type `HASH` as the LaunchDarkly docs suggested that `key` represents a unique key for each item. I suspected from this error that more attributes were required, and had to dig through the [SDK code](https://github.com/launchdarkly/go-server-sdk-dynamodb/blob/c24c46d86519584013185d62e0d75279182ba9cd/dynamodb_impl.go#L325-L326) to figure out what they were. It seems to run correctly now with two attributes; `namespace` of type `HASH`, and `key` of type `RANGE`.

I think it'd be great if the docs could point this out, and even include a sample `aws` CLI invocation to create a table with the correct attributes:

```command
aws dynamodb create-table \
        --endpoint-url http://localhost:8000 \
        --table-name ld-flags \
        --attribute-definitions \
            AttributeName=namespace,AttributeType=S \
            AttributeName=key,AttributeType=S \
        --key-schema \
            AttributeName=namespace,KeyType=HASH \
            AttributeName=key,KeyType=RANGE \
        --billing-mode=PAY_PER_REQUEST
```

**Comment by eli-darkly** [comment]
We do need to clarify these docs. The page you linked to does mention `namespace` and `key` rather than just `key`, but it's not immediately apparent that they are partition key & sort key (a.k.a. hash & range).

Showing a sample AWS command as you suggest might be helpful - however, I'm a little ambivalent about this because we definitely do _not_ want to be misleadingly suggesting options that have nothing to do with the LaunchDarkly requirements, such as `--billing-mode`. I realize that the `create-table` command isn't valid unless you specify those options, but for things like the billing mode and the throughput limits, the developer really needs to understand what those are for and make decisions about them; we don't want anyone to just blindly copy our example.

**Comment by ember-stevens** [comment]
Docs updated on 4/1.
