### ISSUE TITLE
Best Practices Link is broken

### ISSUE THREAD

**Issue by timgilmore** [launchdarkly/LaunchDarkly-Docs#279]
https://docs.launchdarkly.com/guides/flags/creating-flags
The Best practices link at the bottom of the page is now broken.
![image](https://user-images.githubusercontent.com/5649227/180843408-a3c88c48-8b95-4d1c-bd87-a89f896fc9d0.png)

**Comment by scribblingfox** [comment]
@timgilmore Thanks for this PR! You've correctly identified a broken link, and we're on the case! Should be fixed shortly, although it will go to a slightly different location because we've just re-architected how our guides section is laid out. 

This change literally went live less than an hour ago, so thanks for your very speedy feedback!

**Comment by scribblingfox** [comment]
@timgilmore These links are updated now! Give your browser a hard refresh and you should see the destinations change.

Thanks again for your input! You made the docs better for everyone. :)
