### ISSUE TITLE
JS SDK requires String.prototype.startsWith polyfill for IE11

### ISSUE THREAD

**Issue by jameschao** [launchdarkly/LaunchDarkly-Docs#68]
Hi, when suing the JS SDK in IE11, I found out that I needed a polyfill for [`String.prototype.startsWith`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith).

This wasn't listened on your [Requirements and polyfills page](https://docs.launchdarkly.com/sdk/client-side/javascript/requirements-polyfills) so might be good to include that.

**Comment by scribblingfox** [comment]
@jameschao Thanks so much for this issue! In future instances, you'll get a faster response by filing a PR... and when the PR gets merged, you'll have committed to our codebase! 

I've asked our SDK team to update this content. Thanks again!

**Comment by jameschao** [comment]
Hi Sarah, I considered writing a PR but I was in a hurry and it required restructuring some of the doc sections, so I figured it's still better to just notify you first.

**Comment by bwoskow-ld** [comment]
Hi @jameschao ,

The reason that this requirement isn't listed in our documentation is actually quite simple -- it is because we don't intend to require this polyfill. `startsWith` was used by accident in a JavaScript SDK sub-component.

Rather than update our documentation, we'll release a new version of our JS SDK in the next few days with a fix to remove the requirement. I'll comment here when that version is available. There's no need for you to take any action until that time.

Thanks for letting us know about this issue!

**Comment by jameschao** [comment]
Sounds good. Thanks!

**Comment by bwoskow-ld** [comment]
Hi @jameschao ,

Please upgrade to [js-client-sdk version 2.17.6](https://github.com/launchdarkly/js-client-sdk/releases/tag/2.17.6) to get the fix. This fix will also be included in our next React SDK release. Thanks again for letting us know.

Ben

**Comment by jameschao** [comment]
Thanks @bwoskow-ld.
